config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :servers
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_server, only: [:show, :edit, :update, :destroy]

  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

    def set_server
    end

    def server_params
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(page_title)
    content_for(:title) { page_title }
  end

 def bootstrap_class_for flash_type
   { success: "alert-success", error: "alert-danger", alert: "alert-danger", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
 end

 def flash_messages(opts = {})
   flash.each do |msg_type, message|
     concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
       concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
         concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
         concat content_tag(:span, 'Close', class: 'sr-only')
       end)
       concat message
     end)
   end
   nil
 end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-dark bg-primary">
    <div class="container">
    <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2">
      &#9776;
    </button>
    <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
      <%= link_to "Parthenon", root_path, class: "navbar-brand" %>

      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to servers_path, class: 'nav-link' do %>
                <%= fa_icon "server", class: 'fa-fw', text: 'Servers' %>
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to edit_user_registration_path, class: 'nav-link' do %>
                <%= fa_icon "cog", class: 'fa-fw', text: 'Account' %>
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link' do %>
                <%= fa_icon "sign-out", class: 'fa-fw', text: 'Sign Out' %>
            <% end %>
          </li>

        <% else %>
        <li class="nav-item">
            <%= link_to new_user_registration_path, class: 'nav-link' do %>
                <%= fa_icon "user-plus", class: 'fa-fw', text: 'Sign Up' %>
            <% end %>
        </li>

        <li class="nav-item">
            <%= link_to new_user_session_path, class: 'nav-link' do %>
                <%= fa_icon "sign-in", class: 'fa-fw', text: 'Login' %>
            <% end %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Parthenon - <%= yield(:title) %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= flash_messages %>

    <%= yield %>
  </div>
</body>
</html>

app/views/pages/home.html.erb
<% page_title "Home" %>
<div class="card">
  <div class="card-block">
    <div class="jumbotron center">
      <h2>Managing servers got easy</h2>
      <%= link_to 'Get started today', root_path, class: 'btn btn-success' %>
    </div>

    <h1 class="card-title">Welcome to Parthenon!</h1>

    <p class="card-text">We made Parthenon to make running Minecraft servers easier, and fun!</p>
  </div>
</div>

app/views/servers/_form.html.erb
form here

app/views/servers/edit.html.erb
<h1>Editing server</h1>
<p>Fill out the form below to edit a server to control</p>
<%= render 'form' %>

app/views/servers/index.html.erb
<% page_title('Servers') %>
index of servers

app/views/servers/new.html.erb
<% page_title 'Add Server' %>
<h1>Add a server</h1>
<p>Fill out the form below to add a server to control</p>
<%= render 'form' %>

app/views/servers/show.html.erb
Server show page